### PR TITLE
Use `a` instead of lambda reference to window.href

### PR DESCRIPTION
**Pull request by bfu4**
bOON ??!?!???????!?!?!?!?!!?!??!??!??!?!??????

### CODE REVIEW

**Review by looskie — APPROVED** [review]
LGTM

**Review by looskie — CHANGES_REQUESTED** [review]
LGTM

**Comment by boon-cpu** [comment]
idfk I did this originally but the spacing was wrong for 0 reason, it was just adding weirds margins so i did what dries told me to do and it fucking work :+1:

**Comment by boon-cpu** [comment]
lbtm :-1:

**Pull request merged**
